dist: bionic
language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - mysql -e 'CREATE DATABASE feedle;'
  - php artisan migrate --no-interaction -vvv
  - npm ci

before_script:
  - npm run dev
  - php artisan serve &

script:
  - vendor/bin/phpcs --standard=Generic --sniffs=Generic.Commenting.Todo,Generic.CodeAnalysis.UnusedFunctionParameter,Generic.CodeAnalysis.EmptyStatement,Generic.PHP.DeprecatedFunctions app/
  - vendor/bin/phpcs --standard=PSR12 app/
  - vendor/bin/phpunit

after_failure:
  - test -n "$(find storage/logs/ -name '*.log' -print -quit)" && cat storage/logs/*.log
